config/routes.rb
Rails.application.routes.draw do

  get 'contact' => 'home#new'
  get 'search' => 'home#search'
  get 'wx' => 'home#wx'
  post 'wx' => 'home#wx'
  post '/contact'=>'home#contact'

  get 'cooperate' => 'home#cooperate'

  get 'service_mode' => 'home#service_mode'

  get 'about_us' => 'home#about_us'

  get 'team' => 'home#team'

  get 'cases' => 'projects#index'

  resources :project_categories
  resources :projects
  resources :news

  root 'home#index'
  resources :categories do
    resources :projects
  end

  namespace :admin do
    root :to =>'sessions#index'
    get  'login'            =>'sessions#new',      :as  =>:login
    post '/sessions/create' =>'sessions#create',   :as =>:logined
    get 'logout'           =>'sessions#destroy',  :as =>:logout
    resources :project_categories
    resources :projects
    resources :project_photos
    resources :news
  end #namespace /admin

end

app/models/project_photo.rb
class ProjectPhoto < ActiveRecord::Base
  belongs_to :project

  has_attached_file :image,
  :url => '/system/project/:id/:style.:extension',
  :path => ':rails_root/public/system/project/:id/:style.:extension',
  :styles => {:thumb => "100x100", :show => "700x375>", :small_image => "100x50"}

  has_attached_file :small_image,
  :url => '/system/project_smallimage/:id/:style.:extension',
  :path => ':rails_root/public/system/project_smallimage/:id/:style.:extension',
  :styles => {:thumb => "100x100", :show => '125x125'}

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates_attachment_content_type :small_image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/admin/project_photos_controller.rb
# encoding: utf-8
class Admin::ProjectPhotosController < Admin::AdminController
  def index
    @project_photos = ProjectPhoto.order('id desc')
  end

  def new
    @project_photo = ProjectPhoto.new
  end

  def create
    @project_photo = ProjectPhoto.new project_photo_params
    if @project_photo.save
      redirect_to admin_project_photos_path
    else
      render 'new'
    end
  end

  def edit
    @project_photo = ProjectPhoto.find(params[:id])
  end

  def update
    @project_photo = ProjectPhoto.find(params[:id])
    if @project_photo.update_attributes(project_photo_params)
      redirect_to admin_project_photos_path
    else
      redirect_to edit_admin_project_photo_path(@project_photo.id)
    end
  end

  def destroy
    @project_photo = ProjectPhoto.find(params[:id])
    if @project_photo.destroy
      render :json =>{msg: 'ok'}
    else
      render :json =>{msg: 'error'}
    end
  end

  private

  def project_photo_params
    params.require(:project_photo).permit(:project_id, :image, :small_image)
  end

end

app/views/admin/project_photos/edit.html.erb
<div id="content" class="span10">
  <div class="row-fluid sortable ui-sortable">
    <div class="box span12">
      <div class="box-header well" data-original-title="">
        <h2><i class="icon-edit"></i>编辑案例图片</h2>
        <div class="box-icon">
          <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
        </div>
      </div>
      <div class="box-content" style="margin-left:50px">
				<%= form_for @project_photo, url: admin_project_photo_path(@project_photo), method: :post, multipart: true, class: 'form-horizontal' do |f| %>
        <input name="_method" type="hidden" value="put" />
        <fieldset>
          <legend></legend>


          <div class="control-group">
            <label class="control-label" for="cproject_name">所属案例名称</label>
            <div class="controls">
							<%= f.select :project_id, [["请选择",""]]+Project.all.collect{|n| [n.brand_name, n.id]}, :size =>20 %>
            </div>
          </div>

          <div class="control-group" style="margin-bottom:50px">
            <label class="control-label" for="cproject_name">上传大图图片</label>
            <div class="controls">
							<%= f.file_field :image %>最佳宽为700,最佳高为375, 后台会同时自动生成100x50 的小图
            </div>
						<div>
							图片预览:
							<%= image_tag @project_photo.image.url(:thumb), :alt => "" %>
						</div>
          </div>
					
					<% if false %>
          <div class="control-group" style="margin-bottom:50px">
            <label class="control-label" for="cproject_name">上传小图图片</label>
            <div class="controls">
							<%= f.file_field :small_image %>最佳宽为127,最佳高为125
            </div>
						<div>
							图片预览:
							<%= image_tag @project_photo.small_image.url(:thumb), :alt => "" %>
						</div>
          </div>
					<% end %>

          <div class="form-actions">
            <button type="submit" class="btn btn-primary" id="project_create_btn">更新</button>
          </div>
        </fieldset>
        <% end %>

      </div>
    </div><!--/span-->

  </div>
</div>
<script type="text/javascript" src="/js/my97DatePicker/WdatePicker.js"></script>
<!--<script type="text/javascript" src="/js/parsley/i18n/messages.zh-cn.js"></script>-->
<script type="text/javascript" src="/js/parsley/parsley.min.js"></script>
<script type="text/javascript" src="/js/parsley/parsley.extend.js"></script>


<script type="text/javascript">
  $(function (){
  $('#project_create_btn').click(function (){
  $('form').parsley('validate');
  });

  });
</script>

app/views/admin/project_photos/index.html.erb
<div id="content" class="span10">
  <div class="row-fluid sortable ui-sortable">
    <div class="box span12" style="">
      <div class="box-header well" data-original-title="">
        <h2 style="margin-left: 100px;"><a href="<%= new_admin_project_photo_path %>"><i class="icon-edit"></i>创建新的案例图片</a></h2>
        <div class="box-icon">
          <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
        </div>
      </div>
      <div class="box-content">
        <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper" role="grid">
          <table class="table table-striped table-bordered bootstrap-datatable datatable dataTable" id="DataTables_Table_0" aria-describedby="DataTables_Table_0_info">
            <thead>
            <tr role="row">
              <th class="sorting" tabindex="0" rowspan="1" colspan="1" style="width: 45px;">ID</th>
							<th class="sorting" tabindex="0" rowspan="1" colspan="1" style="width: 162px;">案例名称</th>
							<th class="sorting" tabindex="0" rowspan="1" colspan="1" style="width: 162px;">大图</th>
							<th class="sorting" tabindex="0" rowspan="1" colspan="1" style="width: 162px;">小图</th>
              <th class="sorting" tabindex="0" rowspan="1" colspan="1" style="width: 160px;">操作</th>
            </tr>
            </thead>

            <tbody>
            <% @project_photos.each do |photo| %>
                <tr class="<%= cycle('odd', 'even') %>" id="project_photos_<%= photo.id %>">
                  <td class="center"><span class="badge badge-info"><%= photo.id %></span></td>
                  <td class="center"><%= photo.try(:project).try(:brand_name) %></td>
                  <td class="center"><%= image_tag photo.image.url(:thumb) %></td>
                  <td class="center"><%= image_tag photo.image.url(:small_image) %></td>

                  <td class="center">
                    <a class="btn btn-info" href="<%= edit_admin_project_photo_path(photo.id) %>"><i class="icon-edit icon-white"></i>编辑</a>
                    <a class="btn btn-danger" href="javascript: delete_resource('project_photos', <%= photo.id %>)"><i class="icon-trash icon-white"></i>删除</a>
                  </td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div><!--/span-->

  </div>
</div>

app/views/admin/project_photos/new.html.erb
<div id="content" class="span10">
	<div class="row-fluid sortable ui-sortable">
		<div class="box span12">
			<div class="box-header well" data-original-title="">
				<h2><i class="icon-edit"></i>创建新的案例图片</h2>
				<div class="box-icon">
					<a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
				</div>
			</div>
			<div class="box-content">
				
				<%= form_for @project_photo, url: admin_project_photos_path, method: :post, multipart: true, class: 'form-horizontal' do |f| %>

        <fieldset>
          <legend></legend>

          <div class="control-group">
            <label class="control-label" for="cproject_name">所属案例名称</label>
            <div class="controls">
							<%= f.select :project_id, [["请选择",""]]+Project.all.collect{|n| [n.brand_name, n.id]}, :size =>20 %>
            </div>
          </div>

          <div class="control-group">
            <label class="control-label" for="cproject_name">上传大图图片</label>
            <div class="controls">
							<%= f.file_field :image %>最佳宽为700,最佳高为375, 后台会同时自动生成100x50 的小图
            </div>
          </div>

					<% if false %>
          <div class="control-group">
            <label class="control-label" for="cproject_name">上传小图图片</label>
            <div class="controls">
							<%= f.file_field :small_image %>最佳宽为127,最佳高为125
            </div>
          </div>
					<% end %>


          <div class="form-actions">
            <button type="submit" class="btn btn-primary" id="project_create_btn">新建</button>
          </div>
        </fieldset>
				<% end %>

			</div>
		</div><!--/span-->

	</div>
</div>
<script type="text/javascript" src="/js/my97DatePicker/WdatePicker.js"></script>
<!--<script type="text/javascript" src="/js/parsley/i18n/messages.zh-cn.js"></script>-->
<script type="text/javascript" src="/js/parsley/parsley.min.js"></script>
<script type="text/javascript" src="/js/parsley/parsley.extend.js"></script>


<script type="text/javascript">
  $(function (){
  $('#project_create_btn').click(function (){
  $('form').parsley('validate');
  });

  });
</script>