config/routes.rb
Rails.application.routes.draw do

  get 'contact' => 'home#new'
  get 'search' => 'home#search'
  get 'wx' => 'home#wx'
  post 'wx' => 'home#wx'
  post '/contact'=>'home#contact'

  get 'cooperate' => 'home#cooperate'

  get 'service_mode' => 'home#service_mode'

  get 'about_us' => 'home#about_us'

  get 'team' => 'home#team'

  get 'cases' => 'projects#index'

  resources :project_categories
  resources :projects
  resources :news

  root 'home#index'
  resources :categories do
    resources :projects
  end

  namespace :admin do
    root :to =>'sessions#index'
    get  'login'            =>'sessions#new',      :as  =>:login
    post '/sessions/create' =>'sessions#create',   :as =>:logined
    get 'logout'           =>'sessions#destroy',  :as =>:logout
    resources :project_categories
    resources :projects
    resources :project_photos
    resources :news
  end #namespace /admin

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def wx
    render plain: params[:echostr]
  end

  def new
    @contact= Contact.new
  end

  def contact
    @contact= Contact.new(contact_params)
    if @contact.save
      render :contact
    else
      render :new
    end
  end

  def cooperate
  end

  def design_concept
  end

  def partner
  end

  def team
  end

  def search
    keyword = params["keyword"]
    @projects = Project.where(["name like ? or brand_name like ?" , "%#{keyword}%", "%#{keyword}%",])
  end

  private
  def contact_params
    params.permit(:name , :phone, :email, :subject, :content)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about_us.html.erb
# coding: utf-8
<%= content_for :head do %>
<%= stylesheet_link_tag    'reset', 'base', 'global', 'list', 'page', media: 'all',
     'data-turbolinks-track' => true %>
<script type="text/javascript" src="/assets/jquery-1.11.1.min.js"></script>
<script type="text/javascript" src="/assets/main.js"></script>
<% end %>
<div id="content">
  <div class="bx">
   	<div class="content_nav">
   	 	<ul class="fl">
   	 		<li class="no1"><a href="/about_us">关于我们</a></li>
   	 		<li><a href="/service_mode">服务内容</a></li>
   	 		<li><a href="/cooperate">合作方式</a></li>
   	 		<li><a href="/team">作业团队</a></li>
   	 	</ul>
   	 	<span class="fk fr">
   	 	</span>
   	</div>
   	<div class="page_inner">
   	 	<h1>你在寻找一个靠谱的设计合作伙伴？</h1>
   	 	<p>设计合作伙伴？对，应该是设计合作伙伴，而不是设计供应商。供应商只是商，伙伴却可以同舟共济并肩作战！设计公司太多了，在百度或google一下“品牌设计”出来那么多家。他们说他们很牛，他们是国际领先的，亚洲级的，中国顶尖的，全国十强的等等。看起来他们真的很牛很牛。很不好意思，我们没有这些Title，但你可以通过下面信息看到一个真实的新创意……</p>
   	 	<h3>我们很小，和中小企业一起成长，但也能服务世界500强的企业</h3>
   	 	<p>我们是一家小公司，客户很多都是中小企业，从上海、广州等地的高科技成长型企业到长三角一带正在创建自己品牌的外向型企业。 但同时我们也能服务世界500强企业海尔、上海通用别克等客户。</p>
   	 	<h3>我们用创意的概念解决你遇到的生意的问题和挑战</h3>
   	 	<p>品牌策略与设计、标志设计、VI设计、平面印刷品设计，专卖店商业空间设计、网站设计等等，这些我们都可以做。但是我们不局限在这个上面。如果可以更大范围帮助客户的生意解决他们的问题，那我们为什么不可以建议客户走不一样的商业模式，帮助寻找更有力的产品概念，协助开创新的营销渠道？如果这些都是客户生意挑战和问题的话。</p>
   	 	<h3>你将得到高性价比的解决方案</h3>
   	 	<p>设计公司太多了，百度一下“品牌设计”，你会发现很多诸如“国际领先的、亚洲级的、中国顶尖的、全国十佳”的公司。我们不喜欢用这样的词汇来形容自己，实力靠服务品质来体现，品质靠客户口碑来见证。我们也相信明智的客户不买贵的，只选对的。不谈价格，只谈价值。我们的价格不是最低廉的，但是你会发现每一分投资都将和我们给你带来的优秀方案相匹配。</p>
   	 	<h3>我们在上海，但是也可以服务外地的客户</h3>
   	 	<p>深圳、广州、苏州、江西、浙江等等地区都有我们的客户，加拿大、俄罗斯、德国、美国的客户也和我们合作过，甚至于我们还收到过来台湾的设计委托。现在交通、通信、网络这么发达，只要我们都投入一份信任，距离就不是问题。</p>
   	 	<h3>我们都是年轻人但同时也有着丰富的实战经验</h3>
   	 	<p>我们都是具有崭新思维、国际视野的年轻人，除了具有设计方面的专业能力同时也有IT专业、历史专业或经济专业等相关背景。经验丰富、细致耐心、沟通效率高、反应敏捷、高效送出高品质的方案。我们没有业务员，客户都来自于网络或者朋友介绍及客户口碑。项目合作的过程中你将直接与设计师沟通，减少信息传递与臆测而造成的缺失与歧义，工作效率、作品效能都更能令人满意。</p>
   	 	<h3>前期深入了解沟通，然后签订合约、支付预付款才开始正式的合作</h3>
   	 	<p>我们前期深入了解沟通，你的问题、需求、背景完全告诉我们，同时你也了解一下我们的专业能力、相关作品经验及基本的报价。接下来我们明确项目的内容、范围、服务、周期和价格，签订合约，依照不同的项目支付不定额度的预付款才开始正式的合作。 </p>
   	 	<h3>我们很简单，我们爱学习</h3>
   	 	<p>简单做人，用心做事。但是不意味着我们不懂为人处事，我们只是更愿意从简从真精诚合作。
				我们也相信只有不遗余力的去学习、去总结、去实践，我们才能有更好的创意来为我们的客户服务。
			</p>
			<h3>我们欢迎任何形式的合作</h3>
			<p>如果你有一个设计项目，正在寻找合适的公司外包，或者寻找合适的团队一起协作完成，你可以马上联系我们，或许对你来说是一个很好的选择。如果你是市场调研、策划；商业、展示空间；多媒体、网络与技术；工业设计；插画；摄影；影视广告；制作等方面的专业工作室、机构或者个人，我们也乐意与你建立联系与链接，如有相关的项目与需求，我们将第一时间和你联络。</p>
   	</div>
  </div>
</div>
<div class="cl h35"></div>

app/views/home/contact.html.erb
# coding: utf-8
<%= content_for :head do %>
<%= stylesheet_link_tag    'reset', 'base', 'global', 'Contact_us', media: 'all',
     'data-turbolinks-track' => true %>
<script type="text/javascript" src="/assets/jquery-1.11.1.min.js"></script>
<script type="text/javascript" src="/assets/main.js"></script>
<% end %>
<div class="bx">
  <div id="content">
   	<div class="contact fl">
   	 	<div class="img fl"></div>
   	 	<div class="address fl">
   	 	 	<p>地址：中国·上海·闵行区·浦涛路768弄25号704</p>
   	 	 	<p>手机：156-0187-8272</p>
				<p>电话：021-60448799</p>
   	 	 	<p>邮箱：1027392818@qq.com</p>
   	 	 	<p>QQ：1027392818</p>
   	 	 	<p>网址：<a href="http://www.ad-88.com" target="_blank">www.ad-88.com</a></p>
   	 	</div>
   	</div>
   	<div class="fl Contact_Us">
   	 	<h5>Contact Us</h5>
   	 	<div>姓名<input type="text"></div>
      <div>电话<input type="text"></div>
   	 	<div>邮箱<input type="text"></div>
   	 	<div>主题<input type="text"></div>
   	 	<textarea class="ly" clols="275" rows="97"></textarea>
   	 	<br>
   	 	<input class="button" type="button" value="提交">
   	</div>
  </div>
</div>
<div class="cl h315"></div>

app/views/home/cooperate.html.erb
# coding: utf-8
<%= content_for :head do %>
<%= stylesheet_link_tag    'reset', 'base', 'global', 'list', 'cooperate', media: 'all',
     'data-turbolinks-track' => true %>
<script type="text/javascript" src="/assets/jquery-1.11.1.min.js"></script>
<script type="text/javascript" src="/assets/main.js"></script>
<% end %>
<div id="content">
  <div class="bx">
   	<div class="content_nav">
   	 	<ul class="fl">
   	 		<li><a href="/about_us">关于我们</a></li>
   	 		<li><a href="/service_mode">服务内容</a></li>
   	 		<li class="no1"><a href="/cooperate">合作方式</a></li>
   	 		<li><a href="/team">作业团队</a></li>
   	 	</ul>
   	 	<span class="fk fr">
   	 	</span>
   	</div>
   	<div class="cooperate">
   	 	<div class="service">
   	 		<h3>合作方式 / Service</h3>
   	 		<span>&gt; 方案1、年费方式/设计管理</span>
   	 		<p>根据全年常规设计管理工作任务量，签定全年合同，进行月度结算或双月份结算服务佣金。</p>
   	 		<span>&gt; 方案2、项目打包/整体结算</span>
   	 		<p>根据产品上市或更新设计任务工作量，如包装、推广物料、终端店面、媒体广告等进行打报设计和结算。</p>
   	 		<span>&gt; 方案3、单项设计/单项结算</span>
   	 		<p>针对某一具体的设计需求委托，如画册、海报、包装、专卖店等进行设计和结算。</p>
   		</div>
   		<div class="service_bottom">
   	 	  <dl class="bottom_1">
          <dt>明确设计需求</dt>
          <dd><a href="">业务咨询</a></dd>
          <dd><a href="">双方沟通</a></dd>
          <dd><a href="">了解项目</a></dd>
        </dl>
        <dl class="bottom_2">
          <dt>签约合同</dt>
          <dd><a href="">达成共识</a></dd>
          <dd><a href="">付预付款</a></dd>
        </dl>
        <dl class="bottom_3">
          <dt>沟通调整</dt>
          <dd><a href="">评审提案</a></dd>
          <dd><a href="">沟通修改</a></dd>
          <dd><a href="">细节调整</a></dd>
        </dl>
        <dl class="bottom_4">
          <dt>品牌跟踪</dt>
          <dd><a href="">后续延伸服务</a></dd>
          <dd><a href="">视觉拓展</a></dd>
        </dl>
        <dl class="bottom_5">
          <dt>商务沟通</dt>
          <dd><a href="">视觉策略</a></dd>
          <dd><a href="">分享资料</a></dd>
          <dd><a href="">探讨思路</a></dd>
          <dd><a href="">进行报价</a></dd>
        </dl>
        <dl class="bottom_6">
          <dt>设计执行</dt>
          <dd><a href="">视觉规划</a></dd>
          <dd><a href="">设计创作</a></dd>
          <dd><a href="">初步方案</a></dd>
          <dd><a href="">收取进度款</a></dd>
        </dl>
        <dl class="bottom_7">
          <dt>项目验收</dt>
          <dd><a href="">综合分析</a></dd>
          <dd><a href="">项目定位</a></dd>
          <dd><a href="">提交完案</a></dd>
          <dd><a href="">支付尾款</a></dd>
        </dl>
   		</div>
   	</div>
  </div>
</div>

app/views/home/design_concept.html.erb
<%= content_for :head do %>
<link rel="stylesheet" type="text/css" href="/assets/reset.css">
<link rel="stylesheet" type="text/css" href="/assets/base.css">
<link rel="stylesheet" type="text/css" href="/assets/global.css">
<link rel="stylesheet" type="text/css" href="/assets/list.css">
<link rel="stylesheet" type="text/css" href="/assets/mode.css">
<% end %>
<div id="content">
  <div class="bx">
   	<div class="content_nav">
   	 	<ul class="fl">
   	 		<li><a href="">关于我们</a></li>
   	 		<li class="no1"><a href="">服务模式</a></li>
   	 		<li><a href="">包装设计</a></li>
   	 		<li><a href="">合作方式</a></li>
   	 		<li><a href="">作业团队</a></li>
   	 	</ul> 
   	 	<span class="fk fr">
   	 	</span>
   	</div>
   	<div class="mode">
   	 	<h3>服务理念 / Service mode</h3>
   	 	<img src="/assets/xy.png" alt="">
   	</div>
   	<div class="mode_bottom">
   	 	<h3>服务模式 / Service mode</h3>
   	 	<div class="mode_inner">
   	 		<h3>1.品牌策略</h3>
   	 		<p>我们的品牌策略服务包括研究和分析消费者的购物行为、新兴市场趋势及行业竞争格局等。 对准重点消费者的洞察和市场机会的识别作为随后的品牌设计创意和创新的跳板。</p>
   	 		<ul>
   	 			<li>品牌资产分析与定位</li>
   	 			<li>品牌区隔及目标定义</li>
   	 			<li>消费者焦点访谈 </li>
   	 			<li>品牌接触点分析 </li>
   	 			<li>品牌视觉识别系统</li>
   	 			<li>品牌识别策略开发</li>
   	 		</ul>
   	 	</div>
   	 	<div class="mode_inner">
   	 		<h3>2.品牌设计</h3>
   	 		<p class="p2">&nbsp;&nbsp;&nbsp;&nbsp;以品牌视觉图形的情感力量吸引、鼓舞并刺激购买，是我们品牌设计战略的核心要素。从店外门头标牌到店内的一个识别指标架，无不触发品牌识别，强化品牌记忆，促进品牌识别的每个微小细节都被细致筹划雕琢。</p>
   	 		<ul>
   	 			<li>品牌命名</li>
   	 			<li>标志设计</li>
   	 			<li>品牌VI设计系统 </li>
   	 			<li>品牌形象广告创意 </li>
   	 			<li>品牌网站规划 </li>
   	 			<li>商品包装设计</li>
   	 			<li>品牌形象画册</li>
   	 			<li>招商工具包设计</li>
   	 		</ul>
   	 	</div>
   	 	<div class="mode_inner">
   	 		<h3>3.商业空间</h3>
   	 		<p class="p3">成功的品牌环境会充分利用品牌文化影响顾客的购买行为。我们的建筑、室内和平面设计专家团队具有丰富经验协助您拓展强大的品牌愿景。从原型店到复制展店，我们的服务是您高利润和成功购物体验的保证。</p>
   	 		<ul>
   	 			<li>店外建筑设计</li>
   	 			<li>专卖店SI设计系统</li>
   	 			<li>展销空间规划 </li>
   	 			<li>陈列规划及道具设计 </li>
   	 			<li>橱窗设计</li>
   	 			<li>连锁系统原型店设计</li>
   	 		</ul>
   	 	</div>
   	</div>
  </div>
</div>
<div class="cl h86"></div>

app/views/home/index.html.erb
# coding: utf-8
<%= content_for :head do %>
   <%= stylesheet_link_tag    'reset', 'base', 'global', 'index', media: 'all',
     'data-turbolinks-track' => true %>
   <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<% end %>
<div id="banner">
  <div id="chuantong">
    <ul class="tuul">
      <li><a href="#"><%= image_tag "banner_01.png" %></a></li>
      <li><a href="#"><%= image_tag "banner_1.png" %></a></li>
      <li><a href="#"><%= image_tag "banner_2.png" %></a></li>
      <li><a href="#"><%= image_tag "banner_3.png" %></a></li>
    </ul>
    <div class="anniu">
      <span class="leftbut"></span>
      <span class="rightbut"></span>
    </div>
    <ul class="dianul">
      <li class="cur"></li>
      <li></li>
      <li></li>
      <li></li>
    </ul>
  </div>
</div>
<!-- 轮播 -->
<script type="text/javascript">
  chuantong(3000,400,1024);
</script>
<!-- 轮播结束 -->
<div class="cl h25"></div>
<!-- 内容 -->
<div class="bx">
  <div id="content">
    <div class="content_top">
      <ul>
        <li onclick="window.location='/project_categories/1'" >
          <h4 class="h4_1"><a href="/project_categories/1">LOGO设计</a></h4>
        </li>
        <li class="top_1" onclick="window.location='/project_categories/2'">
          <h4 class="h4_2"><a href="/project_categories/2">包装设计</a></h4>
        </li>
        <li onclick="window.location='/project_categories/3'">
          <h4 class="h4_3"><a href="/project_categories/3">品牌推广</a></h4>
        </li>
        <li class="top_1" onclick="window.location='/project_categories/4'">
          <h4 class="h4_4"><a href="/project_categories/4">商业空间</a></h4>
        </li>
        <li onclick="window.location='/project_categories/5'">
          <h4 class="h4_5"><a href="/project_categories/5">房地产整合</a></h4>
        </li>
        <li class="top_2" onclick="window.location='/project_categories/6'">
          <h4 class="h4_6"><a href="/project_categories/6">活动与招商</a></h4>
        </li>
      </ul>
    </div>
    <div class="cl h37"></div>
    <div class="inner">
      <div class="inner_news fl">
        <a href="">>>出未创意设计最新新闻</a>
        <ul>
          <li>2013年，出未创意设计为上海武峰吊顶全案品牌服务</li>
          <li>2013年，出未创意设计为宏标御安府做全案房地产整合</li>
          <li>2011年，出未创意设计与苏州馨可丽家居品牌合作</li>
          <li>2010年，出未创意设计与太原恒大地产签约合作</li>
          <li>2009年，荣获第十六届全球华人广告金犊奖</li>
        </ul>
      </div>
      <div class="inner_news3 fl">
        <p>上海出未创意设计事务所是以创意为主导的策略型品牌商业设计机构。我们坚持为成长中的优秀企业创造具有特属差异化的品牌设计。</p>
        <p>出未创意专长于品牌设计、品牌策划、包装设计、产品外观设计、商业空间设计、网站开发设计、房地产整合营销、公关活动，产品招商等相关策划设计服务。我们极具对全球商业创新有效信息的敏锐捕捉、转化，多维度整合传播及高效执行服务能力。</p>
				<p>
					我们不是一家大集团、大公司，但我们的作业水准可媲美一线城市大公司。
					我们虽小，但可以更灵活的服务大集团甚至500强企业，最主要的是我们具有高性价比的服务质量。
				</p>
      </div>
			<div class="qr_code fl">
				<p><%= image_tag "rq_code.png", width: "150px" %></p>
				<p style="padding-left:5px">更多精彩内容请关注我们</p>
			</div>
    </div>
  </div>
</div>
<div class="cl h25"></div>

app/views/home/new.html.erb
# coding: utf-8
<%= content_for :head do %>
<%= stylesheet_link_tag    'reset', 'base', 'global', 'Contact_us', media: 'all',
     'data-turbolinks-track' => true %>
<script type="text/javascript" src="/assets/jquery-1.11.1.min.js"></script>
<script type="text/javascript" src="/assets/main.js"></script>
<% end %>
<div class="bx">
  <div id="content">
   	<div class="contact fl">
   	 	<div class="img fl"></div>
   	 	<div class="address fl">
   	 	 	<p>地址：中国·上海·闵行区·浦涛路768弄25号704</p>
   	 	 	<p>手机：156-0187-8272</p>
				<p>电话：021-60448799</p>
   	 	 	<p>邮箱：1027392818@qq.com</p>
        <p>QQ：1027392818</p>
        <p>网址：<a href="http://www.ad-88.com" target="_blank">www.ad-88.com</a></p>
      </div>
    </div>
    <div class="fl Contact_Us">
      <h5>Contact Us</h5>
      <form name="contact" method="post" action="contact">
        <div>姓名<input type="text" name="name"></div>
        <div>电话<input type="text" name="phone"></div>
        <div>邮箱<input type="text" name="email"></div>
        <div>主题<input type="text" name="subject"></div>
        <textarea class="ly" clols="275" rows="97" name="content"></textarea>
        <br>
        <input class="button" type="submit" value="提交" >
   	</div>
  </div>
</div>
</form>
<p>
  <% if @contact.errors.any? %>
        <div id="error_explanation">
        <h2><%= pluralize(@contact.errors.count, "error") %>
        prohibited the information from being saved:</h2>
        <ul>
          <% @contact.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  </div>
  </p>
<div class="cl h315"></div>

app/views/home/partner.html.erb
<%= content_for :head do %>
<link rel="stylesheet" type="text/css" href="/assets/reset.css">
<link rel="stylesheet" type="text/css" href="/assets/base.css">
<link rel="stylesheet" type="text/css" href="/assets/global.css">
<link rel="stylesheet" type="text/css" href="/assets/list.css">
<link rel="stylesheet" type="text/css" href="/assets/page.css">
<% end %>
<div id="content">
  <div class="bx">
   	<div class="content_nav">
   	 	<ul class="fl">
   	 		<li class="no1"><a href="">关于我们</a></li>
   	 		<li><a href="">服务模式</a></li>
   	 		<li><a href="">包装设计</a></li>
   	 		<li><a href="">合作方式</a></li>
   	 		<li><a href="">作业团队</a></li>
   	 	</ul> 
   	 	<span class="fk fr">
   	 	</span>
   	</div>
   	<div class="page_inner">
   	 	<h1>你在寻找一个靠谱的设计合作伙伴？</h1>
   	 	<p>设计合作伙伴？对，应该是设计合作伙伴，而不是设计供应商。供应商只是商，伙伴却可以同舟共济并肩作战！设计公司太多了，在百度或google一下“品牌设计”出来那么多家。他们说他们很牛，他们是国际领先的，亚洲级的，中国顶尖的，全国十强的等等。看起来他们真的很牛很牛。很不好意思，我们没有这些Title，但你可以通过下面信息看到一个真实的新创意……</p>
   	 	<h3>我们很小，和中小企业一起成长，但也能服务世界500强的企业</h3>
   	 	<p>我们是一家小公司，客户很多都是中小企业，从上海、广州等地的高科技成长型企业到长三角一带正在创建自己品牌的外向型企业。 但同时我们也能服务世界500强企业海尔、上海通用别克等客户。</p>
   	 	<h3>我们用创意的概念解决你遇到的生意的问题和挑战</h3>
   	 	<p>品牌策略与设计、标志设计、VI设计、平面印刷品设计，专卖店商业空间设计、网站设计等等，这些我们都可以做。但是我们不局限在这个上面。如果可以更大范围帮助客户的生意解决他们的问题，那我们为什么不可以建议客户走不一样的商业模式，帮助寻找更有力的产品概念，协助开创新的营销渠道？如果这些都是客户生意挑战和问题的话。</p>
   	 	<h3>你将得到高性价比的解决方案</h3>
   	 	<p>设计公司太多了，百度一下“品牌设计”，你会发现很多诸如“国际领先的、亚洲级的、中国顶尖的、全国十佳”的公司。我们不喜欢用这样的词汇来形容自己，实力靠服务品质来体现，品质靠客户口碑来见证。我们也相信明智的客户不买贵的，只选对的。不谈价格，只谈价值。我们的价格不是最低廉的，但是你会发现每一分投资都将和我们给你带来的优秀方案相匹配。</p>
   	 	<h3>我们在上海，但是也可以服务外地的客户</h3>
   	 	<p>深圳、广州、苏州、江西、浙江等等地区都有我们的客户，加拿大、俄罗斯、德国、美国的客户也和我们合作过，甚至于我们还收到过来台湾的设计委托。现在交通、通信、网络这么发达，只要我们都投入一份信任，距离就不是问题。</p>
   	 	<h3>我们都是年轻人但同时也有着丰富的实战经验</h3>
   	 	<p>我们都是具有崭新思维、国际视野的年轻人，除了具有设计方面的专业能力同时也有IT专业、历史专业或经济专业等相关背景。经验丰富、细致耐心、沟通效率高、反应敏捷、高效送出高品质的方案。我们没有业务员，客户都来自于网络或者朋友介绍及客户口碑。项目合作的过程中你将直接与设计师沟通，减少信息传递与臆测而造成的缺失与歧义，工作效率、作品效能都更能令人满意。</p>
   	 	<h3>前期深入了解沟通，然后签订合约、支付预付款才开始正式的合作</h3>
   	 	<p>我们前期深入了解沟通，你的问题、需求、背景完全告诉我们，同时你也了解一下我们的专业能力、相关作品经验及基本的报价。接下来我们明确项目的内容、范围、服务、周期和价格，签订合约，依照不同的项目支付不定额度的预付款才开始正式的合作。 </p>
   	 	<h3>我们很简单，我们爱学习</h3>
   	 	<p>简单做人，用心做事。但是不意味着我们不懂为人处事，我们只是更愿意从简从真精诚合作。
				我们也相信只有不遗余力的去学习、去总结、去实践，我们才能有更好的创意来为我们的客户服务。
			</p>
			<h3>我们欢迎任何形式的合作</h3>
			<p>如果你有一个设计项目，正在寻找合适的公司外包，或者寻找合适的团队一起协作完成，你可以马上联系我们，或许对你来说是一个很好的选择。如果你是市场调研、策划；商业、展示空间；多媒体、网络与技术；工业设计；插画；摄影；影视广告；制作等方面的专业工作室、机构或者个人，我们也乐意与你建立联系与链接，如有相关的项目与需求，我们将第一时间和你联络。</p>
   	</div>
  </div>
</div>
<div class="cl h35"></div>

app/views/home/search.html.erb
<%= content_for :head do %>
<%= stylesheet_link_tag    'reset', 'base', 'global', 'list',  media: 'all',
     'data-turbolinks-track' => true %>
  <script type="text/javascript" src="/assets/jquery-1.11.1.min.js"></script>
  <script type="text/javascript" src="/assets/main.js"></script>
<% end %>
<div id="content">
  <div class="bx">
    <div class="content_nav">
      <ul class="fl">
        <li class="no1"><a href="/projects">全部案例</a></li>
        <% ProjectCategory.all.each do |pc| %>
          <li><%= link_to pc.name, project_category_path(pc) %></li>
        <% end %>
      </ul>
      <span class="fk fr"></span>
    </div>
    <div class="inner_img">
      <ul>
        <% @projects.in_groups_of(4).each_with_index do |projects, i| %>
          <% projects.compact.each do |project| %>
            <% if i == 0 %>
              <li class="npt">
            <% else %>
              <li>
            <% end %>
            <div class="img ">
              <%= link_to (image_tag project.project_thumbnail.image.url, width: '220', height: '149'), project_path(project) %>
            </div>
            <span><%= project.name %></span>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<div class="cl h42"></div>