config/routes.rb
Rails.application.routes.draw do

  get 'contact' => 'home#new'
  get 'search' => 'home#search'
  get 'wx' => 'home#wx'
  post 'wx' => 'home#wx'
  post '/contact'=>'home#contact'

  get 'cooperate' => 'home#cooperate'

  get 'service_mode' => 'home#service_mode'

  get 'about_us' => 'home#about_us'

  get 'team' => 'home#team'

  get 'cases' => 'projects#index'

  resources :project_categories
  resources :projects
  resources :news

  root 'home#index'
  resources :categories do
    resources :projects
  end

  namespace :admin do
    root :to =>'sessions#index'
    get  'login'            =>'sessions#new',      :as  =>:login
    post '/sessions/create' =>'sessions#create',   :as =>:logined
    get 'logout'           =>'sessions#destroy',  :as =>:logout
    resources :project_categories
    resources :projects
    resources :project_photos
    resources :news
  end #namespace /admin

end

app/models/project_category.rb
class ProjectCategory < ActiveRecord::Base
  has_many :projects
end

app/controllers/admin/project_categories_controller.rb
# encoding: utf-8
class Admin::ProjectCategoriesController < Admin::AdminController
  def index
    @project_categories = ProjectCategory.order('id desc')
  end

  def new
    #
  end

  def create
    @project_category = ProjectCategory.new project_category_params
    if @project_category.save
      redirect_to admin_project_categories_path
    else
      render 'new'
    end
  end

  def edit
    @project_category = ProjectCategory.find(params[:id])
  end

  def update
    @project_category = ProjectCategory.find(params[:id])
    if @project_category.update_attributes(project_category_params)
      redirect_to admin_project_categories_path
    else
      redirect_to edit_admin_project_category_path(@project_category.id)
    end
  end

  def destroy
    @project_category = ProjectCategory.find(params[:id])
    if @project_category.destroy
      render :json =>{msg: 'ok'}
    else
      render :json =>{msg: 'error'}
    end
  end

  private

  def project_category_params
    params.require(:project_category).permit(:name)
  end

end

app/controllers/project_categories_controller.rb
class ProjectCategoriesController < ApplicationController
  def index
  end

  def show
    @project_category = ProjectCategory.find(params[:id])
    @title = @project_category.name
  end
end

app/helpers/project_categories_helper.rb
module ProjectCategoriesHelper
end

app/views/admin/project_categories/edit.html.erb
<div id="content" class="span10">
  <div class="row-fluid sortable ui-sortable">
    <div class="box span12">
      <div class="box-header well" data-original-title="">
        <h2><i class="icon-edit"></i>编辑案例分类</h2>
        <div class="box-icon">
          <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
        </div>
      </div>
      <div class="box-content">
        <%= form_tag admin_project_category_path, :class =>'form-horizontal' do %>
            <input name="_method" type="hidden" value="put" />
            <fieldset>
              <legend></legend>
              <div class="control-group">
                <label class="control-label" for="ctitle">案例分类名称</label>
                <div class="controls">
                  <input type="text" class="span6 typeahead" id="ctitle" name="project_category[name]" value="<%= @project_category.name %>" data-required="true" data-error-message="案例分类名称!" />
                </div>
              </div>

              <div class="form-actions">
                <button type="submit" class="btn btn-primary" id="project_create_btn">更新</button>
              </div>
            </fieldset>
        <% end %>

      </div>
    </div><!--/span-->

  </div>
</div>
<script type="text/javascript" src="/js/my97DatePicker/WdatePicker.js"></script>
<!--<script type="text/javascript" src="/js/parsley/i18n/messages.zh-cn.js"></script>-->
<script type="text/javascript" src="/js/parsley/parsley.min.js"></script>
<script type="text/javascript" src="/js/parsley/parsley.extend.js"></script>


<script type="text/javascript">
    $(function (){
        $('#project_create_btn').click(function (){
            $('form').parsley('validate');
        });

    });
</script>

app/views/admin/project_categories/index.html.erb
<div id="content" class="span10">
  <div class="row-fluid sortable ui-sortable">
    <div class="box span12" style="">
      <div class="box-header well" data-original-title="">
        <h2 style="margin-left: 100px;"><a href="<%= new_admin_project_category_path %>"><i class="icon-edit"></i>创建新的案例分类</a></h2>
        <div class="box-icon">
          <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
        </div>
      </div>
      <div class="box-content">
        <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper" role="grid">
          <table class="table table-striped table-bordered bootstrap-datatable datatable dataTable" id="DataTables_Table_0" aria-describedby="DataTables_Table_0_info">
            <thead>
            <tr role="row">
              <th class="sorting" tabindex="0" rowspan="1" colspan="1" style="width: 45px;">ID</th>
							<th class="sorting" tabindex="0" rowspan="1" colspan="1" style="width: 162px;">案例分类名称</th>
              <th class="sorting" tabindex="0" rowspan="1" colspan="1" style="width: 160px;">操作</th>
            </tr>
            </thead>

            <tbody>
            <% @project_categories.each do |cat| %>
                <tr class="<%= cycle('odd', 'even') %>" id="project_categories_<%= cat.id %>">
                  <td class="center"><span class="badge badge-info"><%= cat.id %></span></td>
                  <td class="center"><%= cat.name %></td>
                  <td class="center">
                    <a class="btn btn-info" href="<%= edit_admin_project_category_path(cat.id) %>"><i class="icon-edit icon-white"></i>编辑</a>
                    <a class="btn btn-danger" href="javascript: delete_resource('project_categories', <%= cat.id %>)"><i class="icon-trash icon-white"></i>删除</a>
                  </td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div><!--/span-->

  </div>
</div>

app/views/admin/project_categories/new.html.erb
<div id="content" class="span10">
	<div class="row-fluid sortable ui-sortable">
		<div class="box span12">
			<div class="box-header well" data-original-title="">
				<h2><i class="icon-edit"></i> 创建新的案例分类</h2>
				<div class="box-icon">
					<a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
				</div>
			</div>
			<div class="box-content">
				<%= form_tag admin_project_categories_path, :method => :post, :multipart =>true, :class =>'form-horizontal' do %>
        <fieldset>
          <legend></legend>
          <div class="control-group">
            <label class="control-label" for="cbrand_name">案例分类名称</label>
            <div class="controls">
              <input type="text" class="span6 typeahead" id="cbrand_name" name="project_category[name]" data-required="true" data-error-message="名称不能为空!" />
            </div>
          </div>

          <div class="form-actions">
            <button type="submit" class="btn btn-primary" id="project_create_btn">新建</button>
          </div>
        </fieldset>
				<% end %>

			</div>
		</div><!--/span-->

	</div>
</div>
<script type="text/javascript" src="/js/my97DatePicker/WdatePicker.js"></script>
<!--<script type="text/javascript" src="/js/parsley/i18n/messages.zh-cn.js"></script>-->
<script type="text/javascript" src="/js/parsley/parsley.min.js"></script>
<script type="text/javascript" src="/js/parsley/parsley.extend.js"></script>


<script type="text/javascript">
  $(function (){
  $('#project_create_btn').click(function (){
  $('form').parsley('validate');
  });

  });
</script>