config/routes.rb
Rails.application.routes.draw do

  get 'contact' => 'home#new'
  get 'search' => 'home#search'
  get 'wx' => 'home#wx'
  post 'wx' => 'home#wx'
  post '/contact'=>'home#contact'

  get 'cooperate' => 'home#cooperate'

  get 'service_mode' => 'home#service_mode'

  get 'about_us' => 'home#about_us'

  get 'team' => 'home#team'

  get 'cases' => 'projects#index'

  resources :project_categories
  resources :projects
  resources :news

  root 'home#index'
  resources :categories do
    resources :projects
  end

  namespace :admin do
    root :to =>'sessions#index'
    get  'login'            =>'sessions#new',      :as  =>:login
    post '/sessions/create' =>'sessions#create',   :as =>:logined
    get 'logout'           =>'sessions#destroy',  :as =>:logout
    resources :project_categories
    resources :projects
    resources :project_photos
    resources :news
  end #namespace /admin

end

app/models/project.rb
require 'elasticsearch/model'

class Project < ActiveRecord::Base
  belongs_to :project_category
  has_one :project_thumbnail
  has_many :project_photos
  scope :published, -> { where(is_public: true) }

  include Elasticsearch::Model
end

app/controllers/admin/projects_controller.rb
# encoding: utf-8
class Admin::ProjectsController < Admin::AdminController
  def index
    @projects = Project.order('id desc')
  end

  def new
    #
  end

  def create
    @project = Project.new project_params
    @project.project_thumbnail = ProjectThumbnail.new(project_thumbnail_params)
    if @project.save
      redirect_to admin_projects_path
    else
      render 'new'
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if params[:project_thumbnail].present?
      @project.project_thumbnail = ProjectThumbnail.new(project_thumbnail_params)
    end
    if @project.update_attributes(project_params)
      redirect_to admin_projects_path
    else
      redirect_to edit_admin_project_path(@project.id)
    end
  end

  def destroy
    @project = Project.find(params[:id])
    if @project.destroy
      render :json =>{msg: 'ok'}
    else
      render :json =>{msg: 'error'}
    end
  end

  private
  def project_params
    params.require(:project).permit(:name, :brand_name, :company_name, :project_category_id, :service_content, :desc, :is_public)
  end

  def project_thumbnail_params
    params.require(:project_thumbnail).permit(:image)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
  end

  def show
    @project = Project.find(params[:id])
    @title = @project.name
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/admin/projects/edit.html.erb
<div id="content" class="span10">
  <div class="row-fluid sortable ui-sortable">
    <div class="box span12">
      <div class="box-header well" data-original-title="">
        <h2><i class="icon-edit"></i>编辑案例</h2>
        <div class="box-icon">
          <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
        </div>
      </div>
      <div class="box-content">
        <%= form_tag admin_project_path, :multipart =>true, :class =>'form-horizontal' do %>
        <input name="_method" type="hidden" value="put" />
        <fieldset>
          <legend></legend>

          <div class="control-group">
            <label class="control-label" for="cname">案例名称</label>
            <div class="controls">
              <input type="text" class="span6 typeahead" id="cname" name="project[name]" value="<%= @project.name %>" data-required="true" data-error-message="案例名称不能为空!" />
            </div>
          </div>

          <div class="control-group">
            <label class="control-label" for="ctitle">客户品牌名称</label>
            <div class="controls">
              <input type="text" class="span6 typeahead" id="ctitle" name="project[brand_name]" value="<%= @project.brand_name %>" data-required="true" data-error-message="客户品牌名称不能为空!" />
            </div>
          </div>

          <div class="control-group">
            <label class="control-label" for="ccompany_name">客户公司名称</label>
            <div class="controls">
              <input name="project[company_name]" id="ccompany_name" data-required="true" data-error-message="内容不能为空!" value="<%= @project.company_name %>" />
            </div>
          </div>

          <div class="control-group">
            <label class="control-label" for="cproject_category_id">案例所属分类</label>
            <div class="controls">
							<%= select_tag "project[project_category_id]", options_from_collection_for_select(ProjectCategory.all, "id", "name", @project.project_category_id),  prompt: "select category", id: "cproject_category_id"  %>
            </div>
          </div>

          <div class="control-group">
            <label class="control-label" for="cservice_content">服务内容</label>
            <div class="controls">
              <input name="project[service_content]" id="cservice_content" data-required="true" data-error-message="内容不能为空!" value="<%= @project.service_content %>" /></div>
          </div>

          <div class="control-group">
            <label class="control-label" for="cdesc">详细介绍</label>
            <div class="controls">
              <textarea name="project[desc]" id="cdesc" cols="30" rows="10" style="margin: 0; width: 401px; height: 182px;" data-required="true" data-error-message="内容不能为空!"><%= @project.desc %></textarea>
            </div>
          </div>

          <div class="control-group">
            <label class="control-label" for="cimage">列表页缩略图(w220xh150)</label>
            <div class="controls">
              <input type="file" class="span6 typeahead" id="cimage" name="project_thumbnail[image]" />
              <img src="<%= @project.project_thumbnail.image.url %>" />
            </div>
          </div>

          <div class="control-group">
            <label class="control-label" for="cis_public">是否公开</label>
            <div class="controls">
              <input type="checkbox" name="project[is_public]" class="span6 typeahead" id="clink" />
            </div>
          </div>

          <div class="form-actions">
            <button type="submit" class="btn btn-primary" id="project_create_btn">更新</button>
          </div>
        </fieldset>
        <% end %>

      </div>
    </div><!--/span-->

  </div>
</div>
<script type="text/javascript" src="/js/my97DatePicker/WdatePicker.js"></script>
<!--<script type="text/javascript" src="/js/parsley/i18n/messages.zh-cn.js"></script>-->
<script type="text/javascript" src="/js/parsley/parsley.min.js"></script>
<script type="text/javascript" src="/js/parsley/parsley.extend.js"></script>


<script type="text/javascript">
  $(function (){
  $('#project_create_btn').click(function (){
  $('form').parsley('validate');
  });

  });
</script>

app/views/admin/projects/index.html.erb
<div id="content" class="span10">
  <div class="row-fluid sortable ui-sortable">
    <div class="box span12" style="">
      <div class="box-header well" data-original-title="">
        <h2 style="margin-left: 100px;"><a href="<%= new_admin_project_path %>"><i class="icon-edit"></i>创建新的案例</a></h2>
        <div class="box-icon">
          <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
        </div>
      </div>
      <div class="box-content">
        <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper" role="grid">
          <table class="table table-striped table-bordered bootstrap-datatable datatable dataTable" id="DataTables_Table_0" aria-describedby="DataTables_Table_0_info">
            <thead>
            <tr role="row">
              <th class="sorting" tabindex="0" rowspan="1" colspan="1" style="width: 45px;">ID</th>
							<th class="sorting" tabindex="0" rowspan="1" colspan="1" style="width: 162px;">案例列表页缩略图</th>
              <th class="sorting" tabindex="0" rowspan="1" colspan="1" style="width: 162px;">客户品牌名称</th>
              <th class="sorting" tabindex="0" rowspan="1" colspan="1" style="width: 162px;">客户公司名称</th>
              <th class="sorting" tabindex="0" rowspan="1" colspan="1" style="width: 87px;">是否公开</th>
              <th class="sorting" tabindex="0" rowspan="1" colspan="1" style="width: 160px;">操作</th>
            </tr>
            </thead>

            <tbody>
            <% @projects.each do |pro| %>
                <tr class="<%= cycle('odd', 'even') %>" id="projects_<%= pro.id %>">
                  <td class="center"><span class="badge badge-info"><%= pro.id %></span></td>
                  <td class="center"><img src="<%= pro.project_thumbnail.try(:image).try(:url) %>" /></td>
                  <td class="center"><%= pro.brand_name %></td>
                  <td class="center"><%= pro.company_name %></td>
                  <td class="center"><%= pro.is_public ? "是" : "否" %></td>
                  <td class="center">
                    <a class="btn btn-info" href="<%= edit_admin_project_path(pro.id) %>"><i class="icon-edit icon-white"></i>编辑</a>
                    <a class="btn btn-danger" href="javascript: delete_resource('projects', <%= pro.id %>)"><i class="icon-trash icon-white"></i>删除</a>
                  </td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div><!--/span-->

  </div>
</div>

app/views/admin/projects/new.html.erb
<div id="content" class="span10">
	<div class="row-fluid sortable ui-sortable">
		<div class="box span12">
			<div class="box-header well" data-original-title="">
				<h2><i class="icon-edit"></i> 创建新的案例</h2>
				<div class="box-icon">
					<a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
				</div>
			</div>
			<div class="box-content">
				<%= form_tag admin_projects_path, :method => :post, :multipart =>true, :class =>'form-horizontal' do %>
        <fieldset>
          <legend></legend>

          <div class="control-group">
            <label class="control-label" for="cname">案例名称</label>
            <div class="controls">
              <input type="text" class="span6 typeahead" id="cname" name="project[name]" data-required="true" data-error-message="案例名称不能为空!" />
            </div>
          </div>

          <div class="control-group">
            <label class="control-label" for="cbrand_name">客户品牌名称</label>
            <div class="controls">
              <input type="text" class="span6 typeahead" id="cbrand_name" name="project[brand_name]" data-required="true" data-error-message="客户品牌名称不能为空!" />
            </div>
          </div>

          <div class="control-group">
            <label class="control-label" for="ccompany_name">客户公司名称</label>
            <div class="controls">
              <input type="text" class="span6 typehead" name="project[company_name]" id="ccompany_name" data-required="true" data-error-message="客户公司名称不能为空!" />
            </div>
          </div>

          <div class="control-group">
            <label class="control-label" for="cproject_category_id">案例所属分类</label>
            <div class="controls">
							<%= select_tag "project[project_category_id]", options_from_collection_for_select(ProjectCategory.all, "id", "name"), prompt: "select category", id: "cproject_category_id"  %>
            </div>
          </div>

					<div class="control-group">
            <label class="control-label" for="cservice_content">服务内容</label>
            <div class="controls">
              <input type="text" class="span6 typehead" name="project[service_content]" id="cservice_content" data-required="true" data-error-message="服务内容不能为空!" />
            </div>
          </div>

          <div class="control-group">
            <label class="control-label" for="cdesc">详细介绍</label>
            <div class="controls">
              <textarea name="project[desc]" id="cdesc" cols="30" rows="10" style="margin: 0; width: 401px; height: 182px;" data-required="true" data-error-message="详细介绍不能为空!"></textarea>
            </div>
          </div>

          <div class="control-group">
            <label class="control-label" for="cproject_thumbnail">列表页缩略图(w220xh150)</label>
            <div class="controls">
              <input type="file" class="span6 typeahead" id="cproject_thumbnail" name="project_thumbnail[image]" />
            </div>
          </div>

          <div class="control-group">
            <label class="control-label" for="cis_public">是否公开</label>
            <div class="controls">
              <input type="checkbox" class="span6 typeahead" id="clink" name="project[is_public]" />
            </div>
          </div>

          <div class="form-actions">
            <button type="submit" class="btn btn-primary" id="project_create_btn">更新</button>
          </div>
        </fieldset>
				<% end %>

			</div>
		</div><!--/span-->

	</div>
</div>
<script type="text/javascript" src="/js/my97DatePicker/WdatePicker.js"></script>
<!--<script type="text/javascript" src="/js/parsley/i18n/messages.zh-cn.js"></script>-->
<script type="text/javascript" src="/js/parsley/parsley.min.js"></script>
<script type="text/javascript" src="/js/parsley/parsley.extend.js"></script>


<script type="text/javascript">
  $(function (){
  $('#project_create_btn').click(function (){
  $('form').parsley('validate');
  });

  });
</script>